<?php
function sum_menu() {
    $items['sum'] = array(
        'title' => 'Calculate Sum',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sum_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['sum_success_page'] = array(
        'title' => 'Your numbers added',
        'page callback' => 'sum_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function sum_form() {
    $form['top_number'] = array(
        '#title' => 'Top number',
        '#type' => 'textfield',
        '#description' => t('Please enter your starting number'),
    );
    $form['bottom_number'] = array(
        '#title' => 'Bottom number',
        '#type' => 'textfield',
        '#description' => 'Please enter a number to add to the starting number',
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate',
    );
    return $form;
}

function sum_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['top_number'];
    $second_number = $form_state['values']['bottom_number'];
    $sum = $first_number + $second_number;
    $_SESSION['sum'] = $sum;

    $form_state['redirect'] = 'sum_success_page';
}

function sum_success() {
    return 'You calculated a sum! The answer is: ' . $_SESSION['sum'];
}
